// Generated by gencpp from file myrobot_msgs/HardwareStatus.msg
// DO NOT EDIT!


#ifndef MYROBOT_MSGS_MESSAGE_HARDWARESTATUS_H
#define MYROBOT_MSGS_MESSAGE_HARDWARESTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myrobot_msgs
{
template <class ContainerAllocator>
struct HardwareStatus_
{
  typedef HardwareStatus_<ContainerAllocator> Type;

  HardwareStatus_()
    : temeprature(0)
    , are_motors_up(false)
    , debug_message()  {
    }
  HardwareStatus_(const ContainerAllocator& _alloc)
    : temeprature(0)
    , are_motors_up(false)
    , debug_message(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _temeprature_type;
  _temeprature_type temeprature;

   typedef uint8_t _are_motors_up_type;
  _are_motors_up_type are_motors_up;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _debug_message_type;
  _debug_message_type debug_message;





  typedef boost::shared_ptr< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> const> ConstPtr;

}; // struct HardwareStatus_

typedef ::myrobot_msgs::HardwareStatus_<std::allocator<void> > HardwareStatus;

typedef boost::shared_ptr< ::myrobot_msgs::HardwareStatus > HardwareStatusPtr;
typedef boost::shared_ptr< ::myrobot_msgs::HardwareStatus const> HardwareStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myrobot_msgs::HardwareStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace myrobot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'myrobot_msgs': ['/home/marcin/catkin_ws/src/myrobot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe1da4b9c6239c068532b95d312bfc8f";
  }

  static const char* value(const ::myrobot_msgs::HardwareStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe1da4b9c6239c06ULL;
  static const uint64_t static_value2 = 0x8532b95d312bfc8fULL;
};

template<class ContainerAllocator>
struct DataType< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myrobot_msgs/HardwareStatus";
  }

  static const char* value(const ::myrobot_msgs::HardwareStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 temeprature\n\
bool are_motors_up\n\
string debug_message\n\
";
  }

  static const char* value(const ::myrobot_msgs::HardwareStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temeprature);
      stream.next(m.are_motors_up);
      stream.next(m.debug_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HardwareStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myrobot_msgs::HardwareStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myrobot_msgs::HardwareStatus_<ContainerAllocator>& v)
  {
    s << indent << "temeprature: ";
    Printer<int64_t>::stream(s, indent + "  ", v.temeprature);
    s << indent << "are_motors_up: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.are_motors_up);
    s << indent << "debug_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.debug_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYROBOT_MSGS_MESSAGE_HARDWARESTATUS_H
